### ISSUE TITLE
List pending tasks.

### ISSUE THREAD

**Issue by inikoo** [inikoo/maya#8]
Need a list of pending task for the worker.

For example for warehouse worker:
-list of pallet deliveries status=delivered

**Comment by inikoo** [comment]
This is maybe duplicate of #11

**Comment by YudhistiraA** [comment]
hello @inikoo 

![Screenshot_1713166080](https://github.com/inikoo/maya/assets/42015612/feeb6251-f657-4937-aba7-3e53e3c6ca52)


I already have the components for this but I still don't know where to put it  because in some parts of the aiku starting delivery, return doesn't have filtering

have Filter : 
![image](https://github.com/inikoo/maya/assets/42015612/86564734-098e-4c40-9998-2e0d2b5d9a7b)


doesn't have filtering : 
![image](https://github.com/inikoo/maya/assets/42015612/b6a52a1b-c163-4afb-92ac-6a6da88018ed)
![image](https://github.com/inikoo/maya/assets/42015612/8617458e-4ada-46e5-be36-3b9798b3f982)
